AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Serverless patterns - Amazon API Gateway to AWS Lambda to Amazon DynamoDB

Resources:
  LambdaHandler:
    Type: AWS::Serverless::Function
    Description: 'Lambda function to Get and Put data into DynamoDB table'
    Properties:
      FunctionName: LambdaHandler
      Runtime: nodejs16.x
      # CodeUri: src/
      Handler: index.foobar
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Events:
        PutEvent:
          Type: Api
          Properties:
            Path: /
            Method: PUT
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
    Metadata:
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - index.ts
  
  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DynamoTable
Outputs:
  EndpointUrl:
    Description: 'HTTP REST endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev'
